services:
  redis:
    image: redis:7-alpine
    container_name: booking-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
    ports:
      - "5432:5432"
