spring.application.name=booking-system

spring.datasource.url=jdbc:sqlite:booking.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=validate

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100