spring.application.name=booking-system

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

security.jwt.secret=gLs+JfdP/ZYfJKamoDaSMLpBpFGv/v6Fl5BDhUeq7XM=

spring.data.redis.host=${REDIS_HOSTNAME}
spring.data.redis.port=${REDIS_PORT}
