spring.application.name=booking-system

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

security.jwt.secret=gLs+JfdP/ZYfJKamoDaSMLpBpFGv/v6Fl5BDhUeq7XM=

spring.data.redis.host=${REDIS_HOSTNAME}
spring.data.redis.port=${REDIS_PORT}

spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

spring.mail.properties.mail.smtp.properties=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=booking
spring.rabbitmq.password=booking

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-retries=2
spring.rabbitmq.listener.simple.retry.initial-interval=5s
spring.rabbitmq.listener.simple.retry.multiplier=2
spring.rabbitmq.listener.simple.retry.max-interval=10s

spring.rabbitmq.listener.simple.default-requeue-rejected=false

spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true
spring.rabbitmq.template.mandatory=true
spring.rabbitmq.connection-timeout=5s
spring.rabbitmq.channel-rpc-timeout=5s

outbox.poll-delay-ms=5000

rate-limit.login.capacity=5
rate-limit.login.refill-per-minute=5

rate-limit.booking.capacity=20
rate-limit.booking.refill-per-minute=20