logging.level.org.hibernate.SQL=DEBUG

jwt.access-token-expiration=5h

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=20

rate-limit.booking.capacity=100
rate-limit.booking.refill-per-minute=100