<script lang="ts">
	import { onMount } from 'svelte'; import { createService, deleteService, services, updateService } from '$lib/api/services'; import type { Service } from '$lib/api/types'; import Button from '$lib/components/ui/Button.svelte'; import Card from '$lib/components/ui/Card.svelte'; import Input from '$lib/components/ui/Input.svelte'; import Alert from '$lib/components/ui/Alert.svelte'; import Dialog from '$lib/components/ui/Dialog.svelte';
	let items = $state<Service[]>([]); let loading = $state(true); let error = $state(''); let open = $state(false); let editing = $state<Service | null>(null); let name = $state(''); let description = $state(''); let durationMinutes = $state('30'); let price = $state('0'); let saving = $state(false);
	async function load() { loading = true; try { items = (await services()).content; } catch (reason) { error = reason instanceof Error ? reason.message : 'Could not load services.'; } finally { loading = false; } }
	onMount(load); function show(service?: Service) { editing = service ?? null; name = service?.name ?? ''; description = service?.description ?? ''; durationMinutes = String(service?.durationMinutes ?? 30); price = String(service?.price ?? 0); error = ''; open = true; }
	async function save() { saving = true; error = ''; const data = { name, description, durationMinutes: Number(durationMinutes), price: Number(price) }; try { if (editing) await updateService(editing.id, data); else await createService(data); open = false; await load(); } catch (reason) { error = reason instanceof Error ? reason.message : 'Could not save service.'; } finally { saving = false; } }
	async function remove(id: number) { if (!confirm('Delete this service?')) return; try { await deleteService(id); await load(); } catch (reason) { error = reason instanceof Error ? reason.message : 'Could not delete service.'; } }
</script>
<div class="space-y-5"><div class="flex items-center justify-between"><div><h1 class="text-2xl font-semibold">Services</h1><p class="text-sm text-slate-600">Create, update, or remove offered services.</p></div><Button onclick={() => show()}>Add service</Button></div>{#if error}<Alert>{error}</Alert>{/if}<Card>{#if loading}<p class="text-sm text-slate-500">Loading services…</p>{:else}<div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b text-slate-500"><tr><th class="p-2">Name</th><th class="p-2">Duration</th><th class="p-2">Price</th><th></th></tr></thead><tbody>{#each items as service}<tr class="border-b"><td class="p-2"><strong>{service.name}</strong><br /><span class="text-slate-500">{service.description}</span></td><td class="p-2">{service.durationMinutes} min</td><td class="p-2">{service.price}</td><td class="p-2 text-right"><Button variant="outline" onclick={() => show(service)}>Edit</Button> <Button variant="destructive" onclick={() => remove(service.id)}>Delete</Button></td></tr>{/each}</tbody></table></div>{/if}</Card><Dialog bind:open><form class="space-y-3" onsubmit={(event) => { event.preventDefault(); save(); }}><h2 class="text-lg font-semibold">{editing ? 'Edit service' : 'Add service'}</h2>{#if error}<Alert>{error}</Alert>{/if}<label class="block text-sm">Name <Input bind:value={name} required /></label><label class="block text-sm">Description <textarea class="mt-1 w-full rounded-md border p-2" bind:value={description} required></textarea></label><label class="block text-sm">Duration (minutes) <Input bind:value={durationMinutes} type="number" min="0" required /></label><label class="block text-sm">Price <Input bind:value={price} type="number" min="0" step="0.01" required /></label><div class="flex gap-2"><Button type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save'}</Button><Button variant="outline" onclick={() => open = false}>Cancel</Button></div></form></Dialog></div>
