CREATE TABLE idempotency_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    booking_id BIGINT,
    created_at timestamptz NOT NULL,

    CONSTRAINT uk_idempotency_user_key
        UNIQUE (user_id, idempotency_key),

    CONSTRAINT chk_idempotency_status
        CHECK (status IN ('PROCESSING', 'COMPLETED')),

    CONSTRAINT fk_idempotency_user
        FOREIGN KEY (user_id) REFERENCES users (id),

    CONSTRAINT fk_idempotency_booking
        FOREIGN KEY (booking_id) REFERENCES bookings (id)

);